name: io_decorrelation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.*
  - scipy=1.10.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - pandas=2.0.*
  - scikit-learn=1.3.*
  - h5py=3.9.*
  - tqdm=4.65.*
  - notebook=6.5.*
  - jupyterlab=4.0.*
  - pip
  - pip:
    - pymatreader==0.0.31